"""

Django settings for project project.
;Generated by 'django-admin startproject' using Django 3.0.8.
For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/

"""

import os, datetime
from pathlib import Path

from dotenv import load_dotenv
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

POSTGRES_DB = os.environ.get('POSTGRES_DB_NAME', 'dbvat_pro')
POSTGRES_USERNAME = os.environ.get("DJANGO_DB_USER", "neksio")
POSTGRES_PASSWORD = os.environ.get("DJANGO_DB_PASSWORD", '*Beejay123qweasd')
POSTGRES_HOST = os.environ.get("DJANGO_DB_HOST", "db_app")
POSTGRES_PORT = os.environ.get("DJANGO_DB_PORT", 5432)

PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.environ.get("PAYPAL_CLIENT_SECRET")

PAYPAL_API_BASE = os.environ.get("PAYPAL_API_BASE")

TEMPLATE_DIR=os.path.join(BASE_DIR,'template')
STATIC_DIR=os.path.join(BASE_DIR,'static')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = port = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'diamondbox2024@gmail.com'
EMAIL_HOST_PASSWORD = 'mdzbaiviujfrbivs'


CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']


AUTH_USER_MODEL='accounts.Users'
#Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    "corsheaders",
    'rest_framework',
    'django_filters',
    'accounts',
    'api',
    'rest_framework_api_key',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://0.0.0.0:8030",
    "https://api.dbvat.pro",
    "https://www.dbvat.pro",
    "https://dbvat.pro",

]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://0.0.0.0:8030",
    "https://api.dbvat.pro",
    "https://www.dbvat.pro",
    "https://dbvat.pro",
]



if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': POSTGRES_DB,
            'USER': POSTGRES_USERNAME,
            'PASSWORD': POSTGRES_PASSWORD,
            'HOST': POSTGRES_HOST,
            'PORT': POSTGRES_PORT,
        }
    }
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_SSL_REDIRECT = True
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True


else:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


    DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': POSTGRES_DB,
                'USER': POSTGRES_USERNAME,
                'PASSWORD': POSTGRES_PASSWORD,
                'HOST': POSTGRES_HOST,
                'PORT': POSTGRES_PORT,
            }
    }


AUTHENTICATION_BACKENDS = [
    'accounts.sso_handler.MyOIDCABackend',
    'django.contrib.auth.backends.ModelBackend',
]
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'mozilla_django_oidc.contrib.drf.OIDCAuthentication',
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
        'django_filters.rest_framework.DjangoFilterBackend',
    ),

    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',

    }

JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',

    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,

    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,

}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGES = [
    ('en', ('English')),
    ('ar', ('Arabic')),
]
LANGUAGE_CODE = 'en-us'

DEMO = False
TIME_ZONE ='Asia/Riyadh'
USE_I18N = True

USE_L10N = True

USE_TZ = False

# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


STATIC_URL = '/static/'
STATIC_ROOT = "/neksio/static/"



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'SECURITY_PROTOCOL': 'https',
}

#keyclock

OIDC_HOST = os.environ.get("OIDC_HOST", "https://accounts.diamondbox.me")
OIDC_REALM = os.environ.get("OIDC_REALM", "dbvatpro")
OIDC_RP_CLIENT_ID = os.environ.get("OIDC_RP_CLIENT_ID", "backend")
OIDC_RP_CLIENT_SECRET = os.environ.get("OIDC_RP_CLIENT_SECRET", "F65h8yaarscZowrRSPq62axi8cu95Di7")

OIDC_OP_AUTHORIZATION_ENDPOINT = f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo'

TOKEN_EXPIRATION_TIME = os.environ.get("TOKEN_EXPIRATION_TIME", 300)
TOKEN_VERIFY_EXPIRATION = True
TOKEN_VERIFY_SIGNATURE = True
TOKEN_EXPIRATION_LEEWAY = os.environ.get("TOKEN_EXPIRATION_LEEWAY", 60)

OIDC_OP_JWKS_ENDPOINT = 'https://accounts.diamondbox.me/realms/secure/protocol/openid-connect/certs'
OIDC_RP_SIGN_ALGO = os.environ.get("OIDC_RP_SIGN_ALGO", 'RS256')
OIDC_RP_IDP_SIGN_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuT9gRVDxg
f3PqzDmkLuy+nxnk2GatZulnP9JgsWGCu1Gvk4wlMEYYm1Zab0nwBQ
D73ex9YucoLLd7DYOlVpHONwy4q5pOXF12vU/LySD/jXhwJ+DImXvbI
44DEcCxaoRDVyiWkjjvSf7mEd+nWz8CEJVQPTuu85GTPAXzsUbSSgg
32y66uYNNfnF+vYcgIcmIVgKMZ3pHHs9mQKqG8PciEy3Vy10NyAbmS
9fH+1VZQtlbOdYoDWZzhGu60w8nAOpVJYaLdpUofTls76tjs6j0QwKg4
vc7Yq9c7pkDJ/x8gvoqG7CqTesohemv+6jyhVqOh1ovMXu0oX+xJDfo0
23lQIDAQAB
-----END PUBLIC KEY-----"""


OIDC_CALLBACK_REDIRECT_URI = 'http://localhost:8000/api/callback/'
OIDC_RP_SCOPES = 'roles email profile'
OIDC_VERIFY_SSL = False
OIDC_CREATE_USER = True