# Generated by Django 5.1.4 on 2025-02-04 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('StreetName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name')),
                ('BuildingNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number')),
                ('CitySubdivisionName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Subdivision Name')),
                ('CityName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
                ('PostalZone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Zone')),
                ('RegisteredName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Zone')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='vat number')),
                ('TaxScheme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Type')),
                ('xml_text', models.TextField(blank=True, null=True, verbose_name='XML Text')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EgsLocations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_no', models.CharField(blank=True, max_length=16)),
                ('common_name', models.CharField(blank=True, max_length=230, null=True)),
                ('organisation', models.CharField(blank=True, max_length=230)),
                ('organisation_unit', models.CharField(blank=True, max_length=230)),
                ('serial_number', models.CharField(blank=True, max_length=230)),
                ('title', models.CharField(blank=True, choices=[('1000', 'B2B'), ('0100', 'B2C'), ('1100', 'Both')], max_length=230)),
                ('registered_address', models.CharField(blank=True, max_length=230)),
                ('business_category', models.CharField(blank=True, max_length=230, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField(blank=True, choices=[('10', 'Cash,نقدي'), ('30', 'Credit,ذمم'), ('42', 'Bank Transfer,حوالة بنكية'), ('48', 'Bank Card, Visa Mada'), ('1', 'Instrument not defined,اخرى')], null=True)),
                ('icv', models.PositiveBigIntegerField(blank=True, null=True)),
                ('types', models.CharField(blank=True, choices=[('Standard_Invoice', 'Standard Invoice'), ('Standard_credit_note', 'Standard Credit Note'), ('Standard_debit_note', 'Standard Debit Note'), ('Simplified_Invoice', 'Simplified Invoice'), ('Simplified_credit_note', 'Simplified Credit Note'), ('Simplified_debit_note', 'Simplified Debit Note')], max_length=500, null=True)),
                ('invoice_lines', models.JSONField(blank=True, null=True)),
                ('xml_string', models.TextField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, max_length=500, null=True)),
                ('status_response', models.TextField(blank=True, max_length=1500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='api.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.customerdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_key', models.TextField(blank=True, max_length=1000)),
                ('public_key', models.TextField(blank=True, max_length=1000)),
                ('csr', models.TextField(blank=True, max_length=2500)),
                ('csid', models.TextField(blank=True, max_length=3500, null=True)),
                ('csid_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('secret_csid', models.TextField(blank=True, max_length=2500, null=True)),
                ('csid_request', models.TextField(blank=True, max_length=100, null=True)),
                ('x509_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_certificate', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_secret', models.TextField(blank=True, max_length=500, null=True)),
                ('x509_request', models.TextField(blank=True, max_length=100, null=True)),
                ('company', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schemeType', models.CharField(blank=True, choices=[('TIN', 'TIN'), ('GCC', 'GCC'), ('IQA', 'IQA'), ('PAS', 'PAS'), ('CRN', 'CRN'), ('MOM', 'MOM'), ('MLS', 'MLS'), ('700', '700'), ('SAG', 'SAG'), ('OTH', 'OTH')], max_length=50, null=True, verbose_name='Scheme ID')),
                ('schemeNo', models.BigIntegerField(blank=True, null=True, verbose_name='Scheme Number')),
                ('StreetName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name')),
                ('BuildingNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number')),
                ('PlotIdentification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plot Identification')),
                ('CitySubdivisionName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Subdivision Name')),
                ('CityName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
                ('PostalZone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Zone')),
                ('TaxScheme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Type')),
                ('xml_text', models.TextField(blank=True, null=True, verbose_name='XML Text')),
                ('company', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
