# Generated by Django 5.1.4 on 2025-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetail',
            old_name='BuildingNumber',
            new_name='building_number',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='CityName',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='CitySubdivisionName',
            new_name='city_subdivision_name',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='PostalZone',
            new_name='postal_zone',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='RegisteredName',
            new_name='registered_name',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='StreetName',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='customerdetail',
            old_name='TaxScheme',
            new_name='tax_scheme',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='BuildingNumber',
            new_name='building_number',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='CityName',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='CitySubdivisionName',
            new_name='city_subdivision_name',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='PostalZone',
            new_name='postal_zone',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='schemeNo',
            new_name='scheme_no',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='schemeType',
            new_name='scheme_type',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='StreetName',
            new_name='street_name',
        ),
        migrations.RenameField(
            model_name='supplierdetails',
            old_name='TaxScheme',
            new_name='tax_scheme',
        ),
        migrations.RemoveField(
            model_name='supplierdetails',
            name='PlotIdentification',
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='registered_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Zone'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='vat number'),
        ),
    ]
