# Generated by Django 5.1.4 on 2025-02-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_buildingnumber_customerdetail_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Number'),
        ),
    ]
