# Generated by Django 5.1.4 on 2025-02-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscriptionplan_paymenthistory_company_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='types',
            new_name='document_types',
        ),
    ]
