# Generated by Django 5.1.4 on 2025-02-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_types_invoice_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='is_simplified_credit_note',
            field=models.BooleanField(default=False, verbose_name='Is Simplified credit note'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_simplified_debit_note',
            field=models.BooleanField(default=False, verbose_name='Is Simplified debit note'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_simplified_invoice',
            field=models.BooleanField(default=False, verbose_name='Is Simplified Invoice'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_standard_credit_note',
            field=models.BooleanField(default=False, verbose_name='Is Standard credit note'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_standard_debit_note',
            field=models.BooleanField(default=False, verbose_name='Is Standard debit note'),
        ),
        migrations.AddField(
            model_name='production',
            name='is_standard_invoice',
            field=models.BooleanField(default=False, verbose_name='Is Standard Invoice'),
        ),
    ]
