# Generated by Django 5.1.4 on 2025-02-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_production_is_simplified_credit_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_types',
            field=models.CharField(blank=True, choices=[('Standard_invoice', 'Standard Invoice'), ('Standard_credit_note', 'Standard Credit Note'), ('Standard_debit_note', 'Standard Debit Note'), ('Simplified_invoice', 'Simplified Invoice'), ('Simplified_credit_note', 'Simplified Credit Note'), ('Simplified_debit_note', 'Simplified Debit Note')], max_length=500, null=True),
        ),
    ]
