# Generated by Django 5.1.4 on 2025-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_invoice_document_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.TextField(blank=True, choices=[('sandbox', 'Sandbox'), ('production', 'Production')], null=True),
        ),
    ]
