# Generated by Django 5.1.4 on 2025-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='icv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
