# Generated by Django 5.1.4 on 2025-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_invoice_icv'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_qrcode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
