# Generated by Django 5.1.4 on 2025-02-15 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_invoice_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('private_key', models.TextField(blank=True, max_length=1000)),
                ('public_key', models.TextField(blank=True, max_length=1000)),
                ('csr', models.TextField(blank=True, max_length=2500)),
                ('csid', models.TextField(blank=True, max_length=3500, null=True)),
                ('csid_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('secret_csid', models.TextField(blank=True, max_length=2500, null=True)),
                ('csid_request', models.TextField(blank=True, max_length=100, null=True)),
                ('x509_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_certificate', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_secret', models.TextField(blank=True, max_length=500, null=True)),
                ('x509_request', models.TextField(blank=True, max_length=100, null=True)),
                ('is_simplified_invoice', models.BooleanField(default=False, verbose_name='Is Simplified Invoice')),
                ('is_simplified_debit_note', models.BooleanField(default=False, verbose_name='Is Simplified debit note')),
                ('is_simplified_credit_note', models.BooleanField(default=False, verbose_name='Is Simplified credit note')),
                ('is_standard_invoice', models.BooleanField(default=False, verbose_name='Is Standard Invoice')),
                ('is_standard_debit_note', models.BooleanField(default=False, verbose_name='Is Standard debit note')),
                ('is_standard_credit_note', models.BooleanField(default=False, verbose_name='Is Standard credit note')),
                ('company', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox', to='api.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
