# Generated by Django 5.1.4 on 2025-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sandbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
    ]
