# Generated by Django 5.1.4 on 2025-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sandbox_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
