# Generated by Django 5.1.4 on 2025-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_company_sandbox_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='registered_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registered Name'),
        ),
        migrations.AlterField(
            model_name='supplierdetails',
            name='registered_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registered Name'),
        ),
    ]
